[settings]
asdf = false
vfox = true
idiomatic_version_file_enable_tools = []

[settings.cargo]
binstall = false

[settings.python]
compile = false

[tools]
"cargo:cargo-audit" = "latest"
"cargo:cargo-bloat" = "latest"
"cargo:cargo-cache" = "latest"
"cargo:cargo-edit" = "latest"
"cargo:cargo-update" = "latest"
"cargo:gitlogue" = "latest"
"cargo:random-output" = "latest"
"cargo:tealdeer" = "latest"
"cargo:topgrade" = "latest"
"npm:@github/copilot" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:aws-cdk" = "latest"
"npm:tiged" = "latest"
"npm:trash-cli" = "latest"
"npm:wrangler" = "latest"
bat = "latest"
bottom = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
ghq = "latest"
git-cliff = "latest"
hyperfine = "latest"
jq = "latest"
lsd = "latest"
node = "latest"
pnpm = "latest"
python = "latest"
ripgrep = "latest"
ripgrep-all = "latest"
rust = { version = "stable", components = "rust-src,rust-analyzer" }
tokei = "latest"
zoxide = "latest"
