[settings]
asdf = false
vfox = true
idiomatic_version_file_enable_tools = []

[settings.cargo]
binstall = false

[settings.python]
compile = false

[tools]
"cargo:bat" = "latest"
"cargo:bottom" = "latest"
"cargo:cargo-audit" = "latest"
"cargo:cargo-bloat" = "latest"
"cargo:cargo-cache" = "latest"
"cargo:cargo-edit" = "latest"
"cargo:cargo-update" = "latest"
"cargo:fd-find" = "latest"
"cargo:git-cliff" = "latest"
"cargo:lsd" = "latest"
"cargo:mdbook" = "latest"
"cargo:random-output" = "latest"
"cargo:ripgrep" = "latest"
"cargo:ripgrep_all" = "latest"
"cargo:sccache" = "latest"
"cargo:sqlx-cli" = "latest"
"cargo:tauri-cli" = "latest"
"cargo:tealdeer" = "latest"
"cargo:tokei" = "latest"
"cargo:topgrade" = "latest"
"cargo:trunk" = "latest"
"cargo:wgpu-info" = "latest"
"cargo:zoxide" = "latest"
"node" = "latest"
"npm:@github/copilot" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:aws-cdk" = "latest"
"npm:tiged" = "latest"
"npm:trash-cli" = "latest"
"npm:wrangler" = "latest"
"pnpm" = "latest"
"python" = "latest"
"rust" = { version = "stable", components = "rust-src,rust-analyzer" }
