[settings]
asdf = false
vfox = true
idiomatic_version_file_enable_tools = []

[settings.cargo]
binstall = false

[settings.python]
compile = false

[tools]
"cargo:cargo-audit" = "0.22.0"
"cargo:cargo-bloat" = "0.12.1"
"cargo:cargo-cache" = "0.8.3"
"cargo:cargo-edit" = "0.13.8"
"cargo:cargo-update" = "18.0.0"
"cargo:gitlogue" = "0.7.0"
"cargo:random-output" = "0.3.1"
"cargo:tealdeer" = "1.8.1"
"cargo:topgrade" = "16.8.0"
"npm:@github/copilot" = "0.0.394"
"npm:@google/gemini-cli" = "0.26.0"
"npm:aws-cdk" = "2.1103.0"
"npm:tiged" = "2.12.7"
"npm:trash-cli" = "7.1.1"
"npm:wrangler" = "4.61.1"
bat = "0.26.1"
bottom = "0.12.3"
fd = "10.3.0"
fzf = "0.67.0"
gh = "2.86.0"
ghq = "1.8.0"
git-cliff = "2.12.0"
hyperfine = "1.20.0"
jq = "1.8.1"
lsd = "1.2.0"
node = "25.5.0"
pnpm = "10.28.2"
python = "3.14.2"
ripgrep = "15.1.0"
rust = { version = "1", components = "rust-src,rust-analyzer" }
tokei = "14.0.0"
uv = "0.9.28"
zoxide = "0.9.8"
